### ISSUE TITLE
Direct JSON communication between SIP client and homer-app

### ISSUE THREAD

**Issue by latysheff** [sipcapture/homer-app#132]
Hi guys, could you explain, is it possible and what steps needed to directly save parsed SIP messages to homer-app? I'm using Node.js [sip](https://www.npmjs.com/package/sip) module, and it would be an overhead to pack/unpack/parse again, using HEP protocol.

**Comment by lmangani** [comment]
@latysheff the pre-parsed body can be useful for a variety of things and to ease the indexing stage, but unless you have a super-stable and fully predictable JSON schema for your parsed version, and unless can carry the original payload there will be format translations (and field name complexity) even just in order to display traffic in the UI - If you want this to look like SIP you should pack as HEP Type 1 or basically we'd be just moving computing efforts left to right.

This being said, I think its an interesting challenge we should explore, and there are a few ways I can think of depending on your ultimate purpose:

* create a new HEP type w/ JSON SIP body (instead of raw) and we'll implement support in our backends
* bypass and insert JSON as we do for RTC protocols by adding a type to HEPop and inserting directly
* extend HEP-JS to be able to support the SIP-JSON format and let it convert to HEP inline

**Comment by latysheff** [comment]
@lmangani most probably I can match requirements you indicated to avoid any additional conversions.

> * bypass and insert JSON as we do for RTC protocols by adding a type to HEPop and inserting directly

So, currently, some modifications in homer-app are needed? Or it is just configurable?

Options 1 and 3 still have overhead of HEP proto build/parse.

**Comment by adubovikov** [comment]
IMHO the #2 is the best way in this case, just add an custom HEP ID (you can take any from >1000)
and send it to HEPop or to Heplify-server and it will be inserted  into DB. In this case as we discussed already you have to make a mapping array to display correct names for your fields .

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
