### ISSUE TITLE
filter could not be cleared after back to the Home page and search again

### ISSUE THREAD

**Issue by TaurusXY** [sipcapture/homer-app#145]
Hi,

I found the filter could not be clear after back to the Home page and search again.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:
Step1, type in some filter, take the "Destination Host" as an example.
![step1](https://user-images.githubusercontent.com/49503708/59247178-1390b100-8c51-11e9-9643-5663d2788b3e.png)

Step2, Back to the Home page and click search again.
![step2](https://user-images.githubusercontent.com/49503708/59247188-1ab7bf00-8c51-11e9-9534-36dddb1825f1.png)

In the result page, the filter "Destination Host" I typed before is still here.
In my opinion, the filter should be cleared as I've turned back to the home page.
Please correct me if my understanding is improper.
![step3](https://user-images.githubusercontent.com/49503708/59247194-20ada000-8c51-11e9-83e4-d006a5a836c0.png)

**Comment by lmangani** [comment]
Hi @TaurusXY this is actually intentional and part of the "grid" settings persistence. It allows users to extend the query (and table) with additional results without loosing the previous settings, unless manually removed. 

Perhaps we should extend the `clear` form button to also clear grid filters? Community speak out ;)

**Comment by lmangani** [comment]
Please re-test in 7.7 feel free to try it - any input is welcome!
