### ISSUE TITLE
RTP direction

### ISSUE THREAD

**Issue by akam-it** [sipcapture/homer-app#207]
Hello,
sorry, maybe it is not a bug, but a question. (are there any community forum or chats?)

1. Is it possible to show RTP directions(like in sngrep) in Flow tab?
2. I think screen space is not very compatible. for example in attachment two screenshot of one call - sngrep and homer. sngrep have 4 tabs (ip) and homer have 8

![Screenshot from 2019-11-28 17-41-45](https://user-images.githubusercontent.com/1487709/69814970-66adee80-1206-11ea-836f-fd473dbac4d1.png)
![Screenshot from 2019-11-28 17-41-28](https://user-images.githubusercontent.com/1487709/69814972-66adee80-1206-11ea-8ae3-047bcd6869a8.png)

**Comment by lmangani** [comment]
Thanks for the report! 
It's funny because the reason it has 8 instead of 4 is because its showing the RTCP/SDP flows which is exactly what I think you were asking? So the answer to question 2) is question 1) and the last 2 columns are reports from the media streams. Homer's agents don't do RTP so that's RTCP and might have the private IPs of the devices, etc.

This said, this version is about to be obsoleted and obliterated for a much better one - Please update your setup to the 7.7 homer-app Alpha to enjoy the actual version we're about to release ;)
