### ISSUE TITLE
Questions related to homer integrations

### ISSUE THREAD

**Issue by ishvaram** [sipcapture/homer-app#385]
Hi @adubovikov & @lmangani 
I have a couple of questions that I'm not able to get an answer from the documentation that?

1. To achieve all the features of Homer (SIP flow visualization, Grafana metrics integration, SIP stats aggregated view INVITE, 4xx, 5xx, Alerting, Loki), Can we just use any one of the DataStore, like PostgreSQL, ES? 
2. Is it possible to extract RTP information from my Asterisk(1.8.32) and Kamailio (5.5.3) using Captagent or Kamailio's Native HEP?
3. Does the Homer app has RBAC?
4. What is the latest stable tag/branch which I can use configure homer-app to achieve all of the above issues? (vague question though, but there were a couple of issues that I faced while checking out go branch source with dist, where few things are not working. And I've gone through the issue list checked out specific tag then it worked)
5. Without any time series DB like influxdb can I use Postgres for alerting? with just PostgreSQL as the main DataStore what and all can be achieved?
6. I see InfluxDB metrics, Grafana metrics, Prometheus metrics - For Prometheus and Grafana we can add a data source as influx DB right/ any other Open time series DB? How do we distinguish between these metrics and what and all datastore need to be set up to use these Metrics widgets 

Apologies for the

**Comment by lmangani** [comment]
Hi @ishvaram 

Thanks for getting deeper into HOMER! Many questions here, almost none about homer-app but I'll try tackle a few:

1. HOMER 7.x is dynamic. Meaning there's many ways (some open ended) to obtain the same results with different components. The HOMER UI is focusing on the PostgreSQL integration and integrating with Grafana which supports most of the backends we can write to, but the idea is one can make their own flavor. To achieve all features, you can refer to the examples on the homer7-docker repository, which contains working configurations, etc you can use on any real system too.
If you want a fully round system, you'll need Postgres, Grafana/Loki and either of InfluxDB or Prometheus.

2. YES/NO. Asterisk/RTPEngine/RTPProxy/etc built in HEP modules will send RTCP reports to HOMER, which we'll track and report to, while actual passive RTP analysis (which is way more intensive and intricate) is one of the features we provide through our licensed agents at QXIP and alongside HEPIC, it sponsors HOMER's OSS development. This said, HEP is an open standard and we provide a ready format to deliver RTP statistics back to the platform for developers to use this in their applications natively. 

3. Role based access control rudiments are available in the application, and the framework provides rudiments to use them in/out to modify data. Up to the implementer as of how to use them.

4. Not sure what you mean, I would suggest opening a separate issue for this.

5. Yes you can do whatever you want with the data. If you want timeseries, Telegraf can convert them to any format - I've provided an example to use TImescaleDB for example (also PGSql based) but in general, we invite users to make their own recipes using the backend they prefer based on their needs whenever possible.

6. This is a broad question, cannot be answered in a few lines. If you break it down in a more specific way, please open a new thread for it to be discussed.

I hope this helps!

Since this is not an issue, I'll close it but feel free to keep on commenting if needed.
