### ISSUE TITLE
Dockerhub image tags

### ISSUE THREAD

**Issue by mikeharrisontelia** [sipcapture/homer-app#419]
Hi,

I would like to know if it's possible when you push images to [dockerhub](https://hub.docker.com/r/sipcapture/webapp)
If you could please tag them with the correct version instead of overwriting the latest tag.

**Comment by lmangani** [comment]
Hi @mikeharrisontelia 
Thanks this is of course a good approach in general but we currently do not consider the docker containers anything more than a demo platform, and since latest is the only supported version due to the high number of releases we're pushing out the current approach is simpler - this said, we should and will start tagging stable releases in between major feature implementations.

**Comment by mikeharrisontelia** [comment]
Thanks, @lmangani.

I will build this and heplify-server from source for now. 

In my use case, I spin up and tear down these environments daily and run these services on an AWS container platform.

Is there any specific reason that Docker containers are not considered production-ready?

**Comment by lmangani** [comment]
I did not say they are unstable, just only used by us as a demo/CI platform - Packages are considered the only stable source.
Please consider sponsoring this effort and the project if that's important to your deployment ;)
